contact/urls.py
from django.urls import path

from contact.views import *

app_name = 'contact'

urlpatterns = [
    path('contact-form', ContactView.as_view(), name='contact-form'),
    path('contact-success', ContactSuccessView.as_view(), name='contact-success'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from portfolio.views import *

app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
    path('', HomePageView.as_view(), name="home"),
]

accounts/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from accounts.managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports email instead of username"""
    email           = models.EmailField(unique=True)
    password        = models.CharField(max_length=100, validators=[MinLengthValidator(5)])
    name            = models.CharField(max_length=100)

    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

contact/models.py
from django.core import validators
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Budget(models.Model):
    min = models.PositiveIntegerField()
    max = models.PositiveIntegerField()

    def __str__(self) -> str:
        return f'${self.min}-{self.max}'


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class Project(models.Model):
    client = models.ForeignKey('Client', on_delete=models.CASCADE)
    budget = models.ForeignKey('Budget', on_delete=models.CASCADE)
    description = models.TextField()

    

core/models.py
from django.db import models

# Create your models here.

contact/forms.py
from core.forms import BootstrapModelForm
from django import forms
from django.core.mail import mail_admins, send_mail
from django.forms import widgets

from contact.models import Client, Project


class ClientForm(BootstrapModelForm):
    email = forms.EmailField(widget=widgets.EmailInput(attrs={ 'placeholder': 'Your email' }))

    class Meta:
        model = Client
        fields = ['name']
        widgets = {
            'name': widgets.TextInput(attrs={ 'placeholder': 'Your name' })
        }

    def update_client(self, client):
        client_fields_updated = False
        for key, value in self.cleaned_data.items():
                if getattr(client, key) != value:
                    client_fields_updated = True
                    setattr(client, key, value)
        if client_fields_updated:
            client.save()
            
        return client

    def save(self):
        """
            Check if client with same email already exists, if so update the fields if needed and returns the client
            otherwise create a new client
        """
        client = None
        try:
            client = Client.objects.get(email=self.cleaned_data['email'])
            return self.update_client(client)
        except Client.DoesNotExist:
            return Client.objects.create(**self.cleaned_data)


class ProjectForm(BootstrapModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['budget'].empty_label = 'Project Budget'


    class Meta:
        model = Project
        fields = ['budget', 'description']
        widgets = {
            'description': widgets.Textarea(attrs={ 'placeholder': 'Tell us shortly about your project', 'rows': 6 })
        }

    def save(self, client):
        return Project.objects.create(client=client, **self.cleaned_data)

core/forms.py
from django import forms


class BootstrapModelForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

contact/views.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from contact.forms import *


class ContactView(generic.TemplateView):
    template_name = 'contact/contact_form.html'
    success_url = reverse_lazy('contact:contact-success')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["client_form"] = ClientForm()
        context["project_form"] = ProjectForm()
        context.update(kwargs)
        return context

    def post(self, request):
        client_form = ClientForm(request.POST)
        project_form = ProjectForm(request.POST)

        
        if client_form.is_valid() and project_form.is_valid():
            client = client_form.save()
            project_form.save(client=client)
            return HttpResponseRedirect(self.success_url)

        return self.render_to_response(self.get_context_data(client_form=client_form, project_form=project_form))


class ContactSuccessView(generic.TemplateView):
    template_name = 'contact/contact_success.html'

portfolio/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'portfolio/index.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="description" content="UmmahDevs | We make professional websites for our clients that helps them boost their business and approach more audience. We provide cheap solutions of complex problems.">
    <meta property="og:type" content="website">
    <meta propert="twitter:card" content="summary">
    <meta property="og:title" content="UmmahDevs | Imagination to Reality!">
    <meta propert="twitter:title" content="UmmahDevs | Imagination to Reality!">
    <meta property="og:description" content="UmmahDevs | We make professional websites for our clients that helps them boost their business and approach more audience. We provide cheap solutions of complex problems.">
    <meta propert="twitter:description" content="UmmahDevs | We make professional websites for our clients that helps them boost their business and approach more audience. We provide cheap solutions of complex problems." >
    <meta property="og:locale" content="en-us" />
    <meta property="og:image" content="{% static "img/favicon.png" %}" />
    <meta propert="twitter:image" content="{% static "img/favicon.png" %}" >
    {% comment %} <meta property="og:url" content="https://sitechecker.pro/"/> {% endcomment %}
    <meta content="ummahdevs, web developer, django developer, laravel developer, nodejs developer, .net developer, html css developer, javascript developer, angular developer, react developer, vue developer" name="keywords" />
    <title>{% block page_title %}Ummah Devs | Imagination to Reality!{% endblock %}</title>

    <!-- Favicons -->
    <link href="{% static "img/favicon.png" %}" rel="icon" />
    <link href="{% static "img/apple-touch-icon.png" %}" rel="apple-touch-icon" />

    <!-- Vendor CSS Files -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link
      href="{% static "vendor/bootstrap-icons/bootstrap-icons.css" %}"
      rel="stylesheet"
    />
    <link href="{% static "vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static "css/style.css" %}" rel="stylesheet" />
    
    {% block header_assets %}{% endblock header_assets %}
    
  </head>

  <body>

    {% block content %}{% endblock content %}

    <div id="preloader"></div>
    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Vendor JS Files -->
   
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="{% static "js/main.js" %}"></script>
    {% block lazy_assets %}{% endblock lazy_assets %}
  </body>
</html>

templates/contact/contact_form.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}Contact US | Ummah Devs - Imagination to Reality!{% endblock %}

{% block header_assets %}
    <link href="{% static "css/contact_form.css" %}" rel="stylesheet" />
{% endblock header_assets %}

{% block content %}

   <header id="header">
      {% include 'includes/top-header.html' %}
    </header>

    <section id="testimonials" class="testimonials section-bg">
      <div class="container">
        <div class="section-title">
          <h1>Provide us your project details</h1>
        </div>
      </div>

      <div class="container">
        <form
          action="{% url 'contact:contact-form' %}"
          method="post"
          role="form"
          class="php-email-form"
        >
          {% comment %} <div class="error-message mb-3">
            {{ client_form.errors  }}
          </div> {% endcomment %}
        
       
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6 form-group">
              {{ client_form.name }}
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
              {{ client_form.email }}
            </div>
          </div>
          <div class="form-group mt-3">
          {{ project_form.budget}}
          </div>
          <div class="form-group mt-3">
            {{ project_form.description }}
          </div>
          <div class="my-3">
            <div class="loading">Loading</div>
            
            <div class="sent-message">
              Your message has been sent. Thank you!
            </div>
          </div>
          <div class="text-center">
            <button type="submit">Send Message</button>
          </div>
        </form>
      </div>
    </section>

    {% include 'includes/footer.html' with with_hire_us=False%}

{% endblock content %}

templates/contact/contact_success.html
{% extends 'base.html' %}
{% load static %}


{% block page_title %}Contact Success | Ummah Devs - Imagination to Reality!{% endblock %}

{% block header_assets %}
    <link href="{% static "css/contact_form.css" %}" rel="stylesheet" />
{% endblock header_assets %}

{% block content %}
    <header id="header">
      {% include 'includes/top-header.html' %}
    </header>

    <section>
        <div class="container">
            <h1>Success</h1>
            <p>We received your proposal, we will contact you soon. Thanks:)</p>
        </div>
    </section>

    {% include 'includes/footer.html' with with_hire_us=False%}

{% endblock content %}

templates/includes/footer.html
<!-- ======= Footer ======= -->
<footer
  id="footer"
  class="footer {% if with_hire_us == False %}footer-mt-sm{% endif %}"
>
  {% if with_hire_us != False %}
  <div class="footer__hire-us">
    <div class="container card-glossy">
      <div class="row align-items-center gy-3 gy-lg-0">
        <div class="col-lg-3">
          <h2 class="fs-3">Start a Project</h2>
        </div>
        <div class="col-lg-6">
          <p>
            Interested in working together? We should queue up a chat. I’ll buy
            the coffee.
          </p>
        </div>
        <div class="col-lg-3">
          <a
            href="{% url 'contact:contact-form' %}"
            class="
              btn btn-primary
              button-rounded-lg
              py-md-3
              px-md-5
              py-2
              px-4
              fs-5
            "
          >
            Lets do it
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <div class="container">
    <h3>Ummah Devs</h3>
    <p>
      We have experience of years making sites for clients helping boosting
      their business. You Think We Create!
    </p>
    {% comment %}
    <div class="social-links">
      <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
      <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
      <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
      <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
      <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
    </div>
    {% endcomment %}
    <div class="copyright">
      &copy; Copyright <strong><span>Ummah Devs</span></strong
      >. All Rights Reserved
    </div>
  </div>
</footer>
<!-- End Footer -->

templates/includes/portfolio/about.html
{% load static %}

<section class="about">
  <div class="container">
    <div class="section-title" data-aos="fade-down">
      <h2>Our Team</h2>
      <p>Want to know about our family and their skills?</p>
    </div>

    <div class="row team-member" data-aos="fade-right">
      <div class="col-lg-4">
        <img
          src="{% static 'img/huzaifa_picture.webp' %}"
          class="img-fluid"
          alt="Huzaifa's Picture"
        />
      </div>
      <div class="col-lg-8 pt-4 pt-lg-0 content">
        <h3>Huzaifa</h3>
        <p class="fst-italic">
          Huzaifa, experience of more than 3 years exploring several
          technologies but with solid grip on angular, nodejs (express, nestjs)
          and Django.
        </p>
        <div class="row">
          <div class="col-lg-6">
            <ul>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Birthday:</strong> <span>5 December 2002</span>
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Facebook:</strong>
                <a href="https://www.facebook.com/HuzaifaQayyum786"
                  >Huzaifa Qayyum</a
                >
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Phone:</strong> <span>+92 300 8342563</span>
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>City:</strong> <span>Rawalpindi, Pakistan</span>
              </li>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul>
              <li>
                <i class="bi bi-chevron-right"></i> <strong>Age:</strong>
                <span>18</span>
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Email:</strong>
                <a href="mailto:huzaifaacf@gmail.com">huzaifaacf@gmail.com</a>
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Degree:</strong> <span>ICS</span>
              </li>
              <li>
                <i class="bi bi-chevron-right"></i>
                <strong>Freelance:</strong> <span>Available</span>
              </li>
            </ul>
          </div>
        </div>
        <p></p>
      </div>
    </div>
  </div>
</section>

templates/includes/portfolio/contact-us.html
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Contact</h2>
    </div>

    <!-- <div class="row mt-1"> -->
    <div class="info">
      <div class="address">
        <i class="bi bi-geo-alt"></i>
        <h4>Location:</h4>
        <p>Rawalpindi, Punjab Pakistan.</p>
      </div>

      <div class="email">
        <i class="bi bi-envelope"></i>
        <h4>Email:</h4>
        <p>huzaifaacf@gmail.com</p>
      </div>

      <div class="phone">
        <i class="bi bi-phone"></i>
        <h4>Call:</h4>
        <p>+92 300 8342563</p>
      </div>
    </div>
  </div>
</section>

templates/includes/portfolio/facts.html
<section id="facts" class="facts">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Facts</h2>
      <p>
        Some facts and statistics of our business and achievements are below.
      </p>
    </div>

    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="count-box card-glossy card-glossy--rounded">
          <i class="bi bi-emoji-smile"></i>
          <span
            data-purecounter-start="0"
            data-purecounter-end="232"
            data-purecounter-duration="1"
            class="purecounter"
          ></span>
          <p>Happy Clients</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-2 mt-md-0">
        <div class="count-box card-glossy card-glossy--rounded">
          <i class="bi bi-journal-richtext"></i>
          <span
            data-purecounter-start="0"
            data-purecounter-end="521"
            data-purecounter-duration="1"
            class="purecounter"
          ></span>
          <p>Projects</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-2 mt-lg-0">
        <div class="count-box card-glossy card-glossy--rounded">
          <i class="bi bi-headset"></i>
          <span
            data-purecounter-start="0"
            data-purecounter-end="1463"
            data-purecounter-duration="1"
            class="purecounter"
          ></span>
          <p>Hours Of Support</p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-2 mt-lg-0">
        <div class="count-box card-glossy card-glossy--rounded">
          <i class="bi bi-award"></i>
          <span
            data-purecounter-start="0"
            data-purecounter-end="25"
            data-purecounter-duration="1"
            class="purecounter"
          ></span>
          <p>Awards</p>
        </div>
      </div>
    </div>
  </div>
</section>

templates/includes/portfolio/header.html
<header id="header">
  {% include 'includes/top-header.html' with mobile_nav_button=True %}

  <nav id="navbar" class="navbar nav-menu">
    <ul>
      <li>
        <a href="#hero" class="nav-link scrollto active"
          ><i class="bx bx-home"></i> <span>Home</span></a
        >
      </li>
      <li>
        <a href="#overview" class="nav-link scrollto"
          ><i class="bx bx-user"></i> <span>About</span></a
        >
      </li>

      <li>
        <a href="#skills" class="nav-link scrollto"
          ><i class="bx bx-book-content"></i> <span>Skills</span></a
        >
      </li>
      <li>
        <a href="#services" class="nav-link scrollto"
          ><i class="bx bx-server"></i> <span>Services</span></a
        >
      </li>

      <li>
        <a href="#contact" class="nav-link scrollto"
          ><i class="bx bx-envelope"></i> <span>Contact</span></a
        >
      </li>
    </ul>
  </nav>
  <!-- .nav-menu -->
</header>

templates/includes/portfolio/hero.html
{% load static %}

<section id="hero">
  <div class="container" data-aos="zoomIn" data-aos-delay="100">
    <div
      class="
        row
        justify-content-between
        align-items-center
        hero__flex-container
      "
    >
      <div class="col-lg-6">
        <h1>Ummah Devs</h1>
        <p>
          We're
          <span
            class="typed"
            data-typed-items="Django, Nodejs, Angular, Bootstrap"
          ></span>
          Developer
        </p>
        <a
          class="
            btn btn-primary
            button-rounded-lg
            py-md-3
            px-md-5
            py-3
            px-5
            mt-md-5 mt-4
            hero__get-started
          "
          href="{% url 'contact:contact-form'%}"
          >Get Started</a
        >
      </div>
      <div class="col-lg-6">
        <img src="{% static "img/web-dev.svg" %}" alt="Dealing clients image"
        class="hero__side-image">
      </div>
    </div>
  </div>
</section>

templates/includes/portfolio/projects.html
{% comment %}
 <script src="{% static "vendor/waypoints/noframework.waypoints.js" %}"></script> 
 <link
      href="{% static "vendor/glightbox/css/glightbox.min.css" %}"
      rel="stylesheet"
    />
{% endcomment %}

<section id="portfolio" class="portfolio section-bg">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
        <h2>Portfolio</h2>
        <p>
            Magnam dolores commodi suscipit. Necessitatibus eius consequatur
            ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam
            quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
            Quia fugiat sit in iste officiis commodi quidem hic quas.
        </p>
        </div>

        <div class="row">
        <div
            class="col-lg-12 d-flex justify-content-center"
            data-aos="fade-up"
            data-aos-delay="100"
        >
            <ul id="portfolio-flters" class="card-glossy">
            <li data-filter="*" class="filter-active">All</li>
            <li data-filter=".filter-app">App</li>
            <li data-filter=".filter-card">Card</li>
            <li data-filter=".filter-web">Web</li>
            </ul>
        </div>
        </div>

        <div
        class="row portfolio-container"
        data-aos="fade-up"
        data-aos-delay="200"
        >
        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-1.jpg" %}"
                class="img-fluid"
                alt="App 1"
            />
            <div class="portfolio-info">
                <h4>App 1</h4>
                <p>App</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-1.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="App 1"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="{% static "img/portfolio/portfolio-1.jpg" %}"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-2.jpg" %}"
                class="img-fluid"
                alt="Web 3"
            />
            <div class="portfolio-info">
                <h4>Web 3</h4>
                <p>Web</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-2.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Web 3"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="{% static "img/portfolio/portfolio-2.jpg" %}"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-3.jpg" %}"
                class="img-fluid"
                alt="App 2"
            />
            <div class="portfolio-info">
                <h4>App 2</h4>
                <p>App</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-3.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="App 2"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="{% static "img/portfolio/portfolio-3.jpg" %}"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-4.jpg" %}"
                class="img-fluid"
                alt="Card 2"
            />
            <div class="portfolio-info">
                <h4>Card 2</h4>
                <p>Card</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-4.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Card 2"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="{% static "img/portfolio/portfolio-4.jpg" %}"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-5.jpg" %}"
                class="img-fluid"
                alt="Web 2"
            />
            <div class="portfolio-info">
                <h4>Web 2</h4>
                <p>Web</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-5.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Web 2"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="{% static '' %}"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-6.jpg" %}"
                class="img-fluid"
                alt="App 3"
            />
            <div class="portfolio-info">
                <h4>App 3</h4>
                <p>App</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-6.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="App 3"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="portfolio-details.html"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-7.jpg" %}"
                class="img-fluid"
                alt="Card 1"
            />
            <div class="portfolio-info">
                <h4>Card 1</h4>
                <p>Card</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-7.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Card 1"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="portfolio-details.html"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-8.jpg" %}"
                class="img-fluid"
                alt="Card 3"
            />
            <div class="portfolio-info">
                <h4>Card 3</h4>
                <p>Card</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-8.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Card 3"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="portfolio-details.html"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
            <div class="portfolio-wrap">
            <img
                src="{% static "img/portfolio/portfolio-9.jpg" %}"
                class="img-fluid"
                alt="Web 3"
            />
            <div class="portfolio-info">
                <h4>Web 3</h4>
                <p>Web</p>
                <div class="portfolio-links">
                <a
                    href="{% static "img/portfolio/portfolio-9.jpg" %}"
                    data-gallery="portfolioGallery"
                    class="portfolio-lightbox"
                    title="Web 3"
                    ><i class="bx bx-plus"></i
                ></a>
                <a
                    href="portfolio-details.html"
                    class="portfolio-details-lightbox"
                    data-glightbox="type: external"
                    title="Portfolio Details"
                    ><i class="bx bx-link"></i
                ></a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
</section>